name: act
model:
  type: act
  name: act
  joint_dim: 9
  action_dim: 8
  obs_horizon: 1
  checkpoint: ""
  stepper_frequency: 5
  global_config: ""
  d_model: 512
  ffn_dim: 3200
  nhead: 8
  enc_layers: 4
  dec_layers: 7
  dropout: 0.1
  num_workers: 4
  image_size: 256
  amp: True
  z_dim: 32
  max_len: 100



trainer:
  seed: 42
  chunk_size: 100
  batch_size: 256
  epochs: 10
  lr: 4e-5
  weight_decay: 0.0
  grad_clip: 1.0
  beta: 10.0
