name: action_chunking_transformer
model:
  type: act
  name: act
  joint_dim: 9
  action_dim: 8
  obs_horizon: 1
  checkpoint: ""
  stepper_frequency: 5
  global_config: ""



trainer:
  seed: 42
  chunk_size: 100
  batch_size: 256
  epochs: 10
  lr: 4e-5
  weight_decay: 0.0
  grad_clip: 1.0
  beta: 10.0
  d_model: 512
  ffn_dim: 3200
  nhead: 8
  enc_layer: 8
  dec_layers: 7
  dropout: 0.1
  num_workers: 4
  image_size: 256
  amp: True