name: diffusion_policy
model:
  type: diffusion            # model type
  name: ConditionalUnet1D
  obs_dim: 10                # observation dimension (should match task)
  action_dim: 8              # action dimension (should match task)
  obs_horizon: 8             # history length for model input
  pred_horizon: 16           # prediction horizon
  action_horizon: 8
  diffusion_steps: 100       # number of diffusion steps
  ConditionalUnet1D:
    input_dim: 8
    global_cond_dim: 80   # e.g., obs_dim * obs_horizon

trainer:
  max_epochs: 100
  lr: 0.001
  weight_decay: 1e-6
  ema: true
  scheduler: cosine          # learning rate scheduler
  batch_size: 256            # default batch size (can be overridden by data)
  log_every_n_steps: 50
  val_every_n_epochs: 10
  num_workers: 4


