name: pizero
model:
  type: PiZeroNet
  name: PiZeroNet
  policy_type: pi0            # 'pi0'
  model_path: lerobot/pi0
  obs_dim: 9 # TODO change it to state_dim
  action_dim: 8         # Action dimension
  obs_horizon: 1        # Observation dimension
  pred_horizon: 1
  action_horizon: 1
  image_dim: (3, 480, 640) # Image dimension (b,c,h,w)

trainer:
  lr: 2e-4
  batch_size: 8
  max_epochs: 10
  num_workers: 2
  use_bf16: true
  weight_decay: 0.0
