name: pizero
model:
  type: PiZeroNet
  name: PiZeroNet
  policy_type: pi0            # 'pi0' or 'smolvla'
  model_path: lerobot/pi0
  obs_dim: 10
  action_dim: 8         # Action dimension
  obs_horizon: 1        # Observation dimension
  pred_horizon: 16
  action_horizon: 1
  image_shape: (3, 480, 640) # Image dimension (b,c,h,w)

trainer:
  lr: 0.001
  batch_size: 256
  max_epochs: 1000
  num_workers: 4
