
simulator:
  name: "franka_pick_and_place"              # A unique name for your simulator node
  backend_type: "pybullet"                # The physics engine we're using
  node_frequency: 240                     # How often your node's step() function runs (Hz)
  config:
    connection_mode: "GUI"                # GUI for visual interface, DIRECT for headless mode
    gravity:                              # Gravity vector [x, y, z] in m/s²
      - 0
      - 0
      - -9.81                             # Standard Earth gravity
    sim_frequency: 240

objects:
  - "objects/table.yaml"
  - "objects/block.yaml"
  - "objects/target.yaml"

robots: 
  - "/nfs/rlteam2/abhineet/dsagent/agent/ark_diffusion_policies_on_franka/diffusion_policy/config/robots/franka.yaml"

sensors:
  - "/nfs/rlteam2/refi/ark/ark_diffusion_policies_on_franka/diffusion_policy/config/sensors/IntelRealSense.yaml"  # Path to robot configuration file


text: "Pick the yellow cube and place it in the white background area of the table"

policy_mode: service

channel_config: ark_ml/arkml/examples/franka_pick_place/franka_config/pizero_io_schema.yaml