simulator:
  name: "franka_pick_and_place"              # A unique name for your simulator node
  backend_type: "pybullet"                # The physics engine we're using
  node_frequency: 240                     # How often your node's step() function runs (Hz)
  config:
    connection_mode: "GUI"                # GUI for visual interface, DIRECT for headless mode
    gravity:                              # Gravity vector [x, y, z] in m/s²
      - 0
      - 0
      - -9.81                             # Standard Earth gravity
    sim_frequency: 240

objects:
  - "objects/table.yaml"
  - "objects/block.yaml"
  - "objects/target.yaml"

robots: 
  - "robots/franka.yaml"

sensors:
  - "sensors/IntelRealSense.yaml"  # Path to robot configuration file
  - "sensors/IntelRealSense_attached.yaml"


channel_config:
  action_channels:
    franka/cartesian_command/sim: task_space_command_t

  observation_channels:
    cube/ground_truth/sim: rigid_body_state_t
    target/ground_truth/sim: rigid_body_state_t
    franka/joint_states/sim: joint_state_t
    franka/ee_state/sim: pose_t
    IntelRealSense/rgbd/sim: rgbd_t
    IntelRealSense_attached/rgbd/sim: rgbd_t
