simulator:
  name: "franka_pick_and_place"              # A unique name for your simulator node
  backend_type: "pybullet"                # The physics engine we're using
  node_frequency: 240                     # How often your node's step() function runs (Hz)
  config:
    connection_mode: "GUI"                # GUI for visual interface, DIRECT for headless mode
    gravity: # Gravity vector [x, y, z] in m/s²
      - 0
      - 0
      - -9.81                             # Standard Earth gravity
    sim_frequency: 240

objects:
  - "objects/table.yaml"
  - "objects/block.yaml"
  - "objects/target.yaml"

robots:
  - "robots/franka.yaml"

sensors:
  - "sensors/IntelRealSense.yaml"  # Path to robot configuration file